// Note: Friday = original Saturday pump workout (moved per user request)
// Saturday and Sunday are both rest days
const DAYS = [
  'monday',
  'tuesday',
  'wednesday',
  'thursday',
  'friday',
  'saturday',
  'sunday',
];

const workoutData = [
  {
    week: 1,
    days: {
      monday: {
        isRestDay: false,
        exercises: [
          {
            order: 1,
            title: 'Back',
            subtitle: 'Meadows row',
            body: 'Do some warm up sets here working up to a tough 8 reps. Once there do 3 total sets. For the first 2 sets the 8th rep should be the last rep you can get with good form. On the 3rd set I want you to really push and do a drop set. Be sure to maintain good form, this is critical! You can also use a t-bar as demonstrated. 3 total work sets',
            rpe: '10',
          },
          {
            order: 2,
            title: 'Back',
            subtitle: 'Smith machine row',
            body: "Set stops up on these so that you can pull from about mid-shin. I want you to rest/pause these meaning set the weight down for a split second to eliminate momentum, and then drive your elbows up toward the ceiling as hard as you can. Try to flex hard at the top too. All 3 of your sets are 8 reps, but it's a pyramid, so only the last set will be the one to failure. The sets preceding will not be to failure. 3 total work sets",
            rpe: '8-10',
          },
          {
            order: 3,
            title: 'Back',
            subtitle: 'One arm barbell row',
            body: "Work your way up to a drop set here. This is going to be your high intensity technique. The way I want you to do it, is say row 50lbs for 8, then 75 for 8, then on your last set you do 100 for 8, drop it to 75 for 6, and then drop to 50 for 6. The first 2 sets won't be to failure, but the last one should be brutal and is beyond normal failure. 3 total work sets",
            rpe: '8-12',
          },
          {
            order: 4,
            title: 'Back',
            subtitle: 'Banded pullovers',
            body: "Now with a full pump these should feel great. We are doing these banded. Do 3 sets of 10 here. Most of your pullovers will be done this style throughout the entire program. Be patient with stretching here. Let your arms come down and stretch a little more each set. Don't push the hard stretch, let it happen on its own to avoid injury. 3 total work sets",
            rpe: '8',
          },
          {
            order: 5,
            title: 'Abs',
            subtitle: 'Decline bench leg raises',
            body: 'Do 4 sets close to failure here. 4 total work sets',
            rpe: '9',
          },
          {
            order: 6,
            title: 'Calves',
            subtitle: 'Standing raises',
            body: 'Once warmed up, do 2 sets where you do 10 full range reps, followed by 10 partials out of the bottom, followed by a 10 second stretch to end the set. Take note of your weight, I want you to do more weight on Thursday. 2 total work sets',
            rpe: '10-11',
          },
        ],
      },
      tuesday: {
        isRestDay: false,
        exercises: [
          {
            order: 1,
            title: 'Chest',
            subtitle: 'Slight incline dumbell press',
            body: "Work your way up doing sets of 8 here. Keep going until you barely get 8 reps. The last set should be a drop set to total failure. The sets working up to it, will obviously not be. We will call this 3 working sets. Let's lock these out and really focus on the contraction for maximum activation. 3 total work sets",
            rpe: '8-10',
          },
          {
            order: 2,
            title: 'Chest',
            subtitle: 'Incline barbell press',
            body: 'I want you to do sets of 6 here moving up in weight as you go. Once you can barely squeeze out 6, that is the last set. 3 total work sets',
            rpe: '8-10',
          },
          {
            order: 3,
            title: 'Chest',
            subtitle: 'Machine press',
            body: 'Your high intensity technique here today is a cluster set. Find a weight that is a tough 15. Now what I want you to do, is go to failure with it, then pause for 45 seconds and go to failure again, and then repeat one more time. My reps looked like this --> 15, 11, 7. 1 total work set',
            rpe: '11',
          },
          {
            order: 4,
            title: 'Chest',
            subtitle: 'Machine flye',
            body: 'Arch your chest, lift your sternum and get a nice big stretch on these. I want you to come up 3/4 of the way to ensure we keep tension on the chest. Do 3 sets of 8 here and after the last rep on each set, sit in the stretch position (about 1/4 of the way up) for 10 seconds. 3 total work sets',
            rpe: '10',
          },
          {
            order: 5,
            title: 'Shoulders',
            subtitle: 'Machine rear delts/reverse pec deck',
            body: "Do 3 sets of 25 reps. I want 60 second breaks here. 3 total work sets. The RPE will climb on this, as you will really have to fight to the 25 on the last set. The first 1 or 2 won't be as bad.",
            rpe: '8-11',
          },
          {
            order: 6,
            title: 'Shoulders',
            subtitle: 'Dumbell side laterals',
            body: "Same thing here for the rep scheme. Do 3 sets of 25 reps. I want 60 second breaks here. 3 total work sets. The RPE will climb on this, as you will really have to fight to the 25 on the last set. The first 1 or 2 won't be as bad.",
            rpe: '8-11',
          },
          {
            order: 7,
            title: 'Shoulders',
            subtitle: 'Front barbell raises',
            body: 'Same thing here for the rep scheme. Do 3 sets of 25 reps. I want 60 second breaks here. 3 total work sets. Just come up to eye level. Going past that causes the traps to engage much more.',
            rpe: '8-11',
          },
        ],
      },
      wednesday: {
        isRestDay: false,
        exercises: [
          {
            order: 1,
            title: 'Legs',
            subtitle: 'Lying leg curl',
            body: 'Work your way up doing sets of 10 here. Once you are completely warmed up I want you to do 3 sets of 10 with additional eccentric resistance. Come a rep or two shy of failure. The eccentric loading should be done through the first 3/4 range of motion, let off of it when your hams are stretched out at the bottom. 3 total work sets',
            rpe: '9',
          },
          {
            order: 2,
            title: 'Legs',
            subtitle: 'Barbell squats',
            body: "Do a few sets of 15 to get warmed up and then go to sets of 8. Keep doing 8 until you can just barely get 8. That will be your last set. We will call this 3 total sets. I don't want you to actually fail on the 8th rep, but I want it to be hard. 3 total work sets",
            rpe: '7-9',
          },
          {
            order: 3,
            title: 'Legs',
            subtitle: 'Leg press',
            body: "Use the foot placement you feel most comfortable in. Work up to a weight you can do for 20 reps, and do a cluster set with it. Do 20 reps, rest 45 seconds and knock out more, and then repeat one more time. On this, don't hit failure and get crushed in the leg press, but challenge yourself to push harder than ever. 1 total work set",
            rpe: '9',
          },
          {
            order: 4,
            title: 'Legs',
            subtitle: 'Barbell stiff legged deadlift',
            body: 'Your quads are going to be wobbly, so be careful here. I want 3 sets of 8 here. Get a slight knee bend on these. Come up 3/4 of the way here to keep constant tension on hams. Get a good stretch also. 3 total work sets',
            rpe: '8-9',
          },
        ],
      },
      thursday: {
        isRestDay: false,
        exercises: [
          {
            order: 1,
            title: 'Triceps',
            subtitle: 'Single handle pushdowns',
            body: 'Drive the weight straight down and come just short of lockout to create massive tension on your tris. Do several warm ups so your tris are firing, and elbows thoroughly warmed up. Now knock out 3 sets of 10 with 60 second breaks. 3 total work sets',
            rpe: '8-9',
          },
          {
            order: 2,
            title: 'Triceps',
            subtitle: 'Dip machine',
            body: "If you don't have a machine you can always do old school dips between benches. Do 3 sets of 10 again with 60 second breaks. Don't lock these all the way out either. 3 total work sets",
            rpe: '8-9',
          },
          {
            order: 3,
            title: 'Triceps',
            subtitle: 'Seated overhead rope extensions',
            body: 'Do 3 sets of 10 here. Do not lock these out either. In fact, after the last rep on each set, hold the stretch position for 15 seconds. 3 total work sets',
            rpe: '9',
          },
          {
            order: 4,
            title: 'Biceps',
            subtitle: 'Hammer curls',
            body: 'You have to crush the brachialis for massive arms. Do 3 sets of 10 here squeezing as hard as you can. Keep rest breaks to 60 seconds on these. 3 total work sets',
            rpe: '8-9',
          },
          {
            order: 5,
            title: 'Biceps',
            subtitle: 'Ez bar curl',
            body: 'On these I want you to do 3 sets of 8 with 60 second breaks. 3 total work sets',
            rpe: '8-9',
          },
          {
            order: 6,
            title: 'Biceps',
            subtitle: 'EZ bar preacher curl',
            body: 'Do 3 sets of 10 here but take 90 seconds in between sets. Also after each set stretch your biceps out. Place your hand against a pole or machine with palms facing down and apply pressure to stretch the muscle. Hold each stretch for 15 seconds. 3 total work sets',
            rpe: '9',
          },
          {
            order: 7,
            title: 'Abs',
            subtitle: 'Rope crunches',
            body: 'Do 4 sets to failure here. 4 total work sets',
            rpe: '9',
          },
          {
            order: 8,
            title: 'Calves',
            subtitle: 'Seated toe raises',
            body: 'Simply do 2 sets of 15 here after you are very warmed up. Get a nice deep stretch on all reps. 2 total work sets',
            rpe: '9-10',
          },
        ],
      },
      // Friday = original Saturday pump workout
      friday: {
        isRestDay: false,
        exercises: [
          {
            order: 1,
            title: 'Chest',
            subtitle: 'Machine press',
            body: 'After warming up, do 12 full range of motion reps with a pause and flex at the end of each rep. Stop just short of failure. 3 total work sets',
            rpe: '8-9',
          },
          {
            order: 2,
            title: 'Chest',
            subtitle: 'Flat dumbell press',
            body: '3 sets of 8 here with a full range of motion. 3 total work sets',
            rpe: '8-9',
          },
          {
            order: 3,
            title: 'Chest',
            subtitle: 'Incline fly',
            body: 'Only come up 3/4 of the way so we keep tension on the pecs. Do 3 sets of 12 here. 3 total work sets',
            rpe: '8-9',
          },
          {
            order: 4,
            title: 'Back',
            subtitle: 'Single arm supinated pulldown',
            body: 'Use those single handles. Do 3 sets of 10. 3 total work sets',
            rpe: '8-9',
          },
          {
            order: 5,
            title: 'Back',
            subtitle: 'Cable row',
            body: 'Use a close grip attachment. Do 3 sets of 8 here with a full range of motion but on the negative/eccentric, go slow using a 5 second count. Feel the crazy tension in your lats as you lower it. 3 total work sets',
            rpe: '8-9',
          },
          {
            order: 6,
            title: 'Back',
            subtitle: 'Chins',
            body: 'If you need to use the assist machine feel free. Use a medium pronated grip. Do 3 sets to failure which should be around 12 reps. On these rest 90 seconds, not 60. Only come up 3/4 of the way so we keep tension on the lats. 3 total work sets',
            rpe: '10',
          },
          {
            order: 7,
            title: 'Shoulders',
            subtitle:
              'Rear dumbell laterals / Machine cable side laterals superset',
            body: 'Exercise #1 – Rear Dumbell laterals. Exercise #2 – Machine/cable side laterals. Do 3 rounds. Do 15 reps on both exercises! This will COOK your delts. 6 total work sets',
            rpe: '10',
          },
        ],
      },
      saturday: { isRestDay: true, exercises: [] },
      sunday: { isRestDay: true, exercises: [] },
    },
  },
  {
    week: 2,
    days: {
      monday: {
        isRestDay: false,
        exercises: [
          {
            order: 1,
            title: 'Back',
            subtitle: 'Meadows row',
            body: "This is a repeat from last week, but we are adding a set to increase volume this week. Do some warm up sets here working up to a tough 8 reps. Once there do 4 total sets of 8. On at least one set, try to beat what you did last week for weight, even if it's only a 5 lb plate. The 8th rep (on all sets) should be the last rep you can get with good form. 4 total work sets",
            rpe: '10',
          },
          {
            order: 2,
            title: 'Back',
            subtitle: 'Smith machine row',
            body: "We are going one more week here too, and adding a hard set as well to increase overall volume. Set stops up on these so that you can pull from about mid-shin. All 4 of your sets are 8 reps, but it's a pyramid, so only the last set will be the one to failure. The sets preceding will not be to failure. 4 total work sets",
            rpe: '8-10',
          },
          {
            order: 3,
            title: 'Back',
            subtitle: 'Dumbell row',
            body: "Work your way up to a drop set here like last week on the one arm barbell rows, but now we are using dumbells. Say row 80lbs for 8, then 100 for 8, then on your last set you do 120 for a tough 8, drop it to 100 for 6-8, and then drop to 80 for 6-8 more. The first 2 sets won't be to failure, but the last one should be brutal and is beyond normal failure. 3 total work sets",
            rpe: '8-12',
          },
          {
            order: 4,
            title: 'Back',
            subtitle: 'Rack pulls',
            body: 'Do these from mid-shin. Work up to a pretty heavy 5 reps, and do 3 sets of 5. Leave 2 reps in the tank on each one. 3 total work sets',
            rpe: '8',
          },
          {
            order: 5,
            title: 'Back',
            subtitle: 'Hang from chin up bar',
            body: "Put a weight belt on with some weight and let's hang and stretch those lats. Stretch for as long as you can, shoot for 60 seconds.",
            rpe: null,
          },
          {
            order: 6,
            title: 'Abs',
            subtitle: 'Decline bench leg raises',
            body: 'Do 4 sets close to failure here. 4 total work sets',
            rpe: '9',
          },
          {
            order: 7,
            title: 'Calves',
            subtitle: 'Standing raises',
            body: 'Once warmed up, do 3 sets where you do 10 full range reps, followed by 10 partials out of the bottom, followed by a 10 second stretch to end the set. Take note of your weight, keep building the weight up on these. 3 total work sets',
            rpe: '10-11',
          },
        ],
      },
      tuesday: {
        isRestDay: false,
        exercises: [
          {
            order: 1,
            title: 'Chest',
            subtitle: 'Flat dumbell press',
            body: "Work your way up doing sets of 8 here. Keep going until you barely get 8 reps. The last set should be to total failure. The sets working up to it, will obviously not be. We will call this 3 working sets. Let's lock these out and really focus on the contraction for maximum activation. 3 total work sets",
            rpe: '8-10',
          },
          {
            order: 2,
            title: 'Chest',
            subtitle: 'Incline barbell press',
            body: 'I want you to do sets of 7 here moving up in weight as you go. Once you can barely squeeze out 7, that is the last set. Push as hard as you can do the same weight you did last week and still get the extra 7th rep on the last set. 3 total work sets',
            rpe: '8-10',
          },
          {
            order: 3,
            title: 'Chest',
            subtitle: 'Machine press',
            body: 'Your high intensity technique here today is once again a cluster set, but we are adding a 4th try with the weight. Find a weight that is a tough 15. My reps looked like this --> 15, 11, 7, 6. 1 total work set',
            rpe: '11',
          },
          {
            order: 4,
            title: 'Chest',
            subtitle: 'Incline pronated dumbell flye',
            body: 'Arch your chest, lift your sternum and get a nice big stretch on these using a pronated grip. I want you to come up 3/4 of the way to ensure we keep tension on the chest. Do 4 sets of 8 here. 4 total work sets',
            rpe: '10',
          },
          {
            order: 5,
            title: 'Shoulders',
            subtitle: 'Machine rear delts/reverse pec deck',
            body: 'Do 3 sets of 15 reps with the same weight. I want 90 second breaks today, slow it down a little. 3 total work sets. The RPE will climb on this, as you will really have to fight to the 15 on the last set.',
            rpe: '8-11',
          },
          {
            order: 6,
            title: 'Shoulders',
            subtitle: 'Dumbell side laterals',
            body: 'Same thing here for the rep scheme. Do 3 sets of 15 reps with the same weight. Take 90 second rest breaks. 3 total work sets.',
            rpe: '8-11',
          },
          {
            order: 7,
            title: 'Shoulders',
            subtitle: 'Dumbell overhead press',
            body: 'Find a weight that is a tough 8 and do 3 sets with it. Bring the dumbells all the way together at the top. 3 total work sets',
            rpe: '9',
          },
        ],
      },
      wednesday: {
        isRestDay: false,
        exercises: [
          {
            order: 1,
            title: 'Legs',
            subtitle: 'Seated leg curl',
            body: 'Work your way up doing sets of 10 here. Once you are completely warmed up I want you to do 3 sets of 10. On your 4th set, do 10 again, but then drop the weight a few plates, and shoot for 10 more, and then drop it again and shoot for another 10. 4 total work sets. The last set is the 12.',
            rpe: '9-12',
          },
          {
            order: 2,
            title: 'Legs',
            subtitle: 'Barbell squats',
            body: "Do the same thing as last week, but let's see if you can beat how much weight you used last week for 8. Do a few sets of 15 to get warmed up and then go to sets of 8. We will call this 3 total sets. 3 total work sets",
            rpe: '7-9',
          },
          {
            order: 3,
            title: 'Legs',
            subtitle: 'Bulgarians drop set of death',
            body: 'Do 3 sets of 8 moving up in weight. On the 4th set, we are going to do a drop set. You do 8 reps, and then you do an iso hold for 8 seconds before dropping down to the next dumbell. Do one leg at a time, and let your partner go before you come back to do the other leg. 4 total work set',
            rpe: '12',
          },
          {
            order: 4,
            title: 'Legs',
            subtitle: 'Barbell stiff legged deadlift',
            body: 'I want you to go down with a slow 5 second count, sit in the stretch, and then come back up 4/5 of the way. Try to get around 10 reps like this. Ensure your back is flat and not rounded as you hold your stretch at the bottom. 1 total work sets',
            rpe: '8-9',
          },
        ],
      },
      thursday: {
        isRestDay: false,
        exercises: [
          {
            order: 1,
            title: 'Triceps',
            subtitle: 'Single handle pushdowns',
            body: 'This is the same as last week, but I want you to do an extra set to add volume. Drive the weight straight down and come just short of lockout. Do several warm ups so your tris are firing, and elbows thoroughly warmed up. Now knock out 4 sets of 10 with 60 second breaks. 4 total work sets',
            rpe: '8-9',
          },
          {
            order: 2,
            title: 'Triceps',
            subtitle: 'Dip machine',
            body: "If you don't have a machine you can always do old school dips between benches. Do 3 sets of 10 again with 60 second breaks. Don't lock these all the way out either. 3 total work sets",
            rpe: '8-9',
          },
          {
            order: 3,
            title: 'Triceps',
            subtitle: 'Incline skullcrushers/extensions',
            body: 'This is simply lying extensions, but you are doing them on an incline bench. This allows you to stretch your triceps much better then lying flat. Do 3 sets of 10 here. Do not lock these out either. In fact, after the last rep on your final set, hold the stretch position for 30 seconds. 3 total work sets',
            rpe: '9',
          },
          {
            order: 4,
            title: 'Biceps',
            subtitle: 'Cross body hammer curls (pinwheel curls)',
            body: 'Do 4 sets of 10 here squeezing as hard as you can. Keep rest breaks to 60 seconds on these. 4 total work sets',
            rpe: '8-9',
          },
          {
            order: 5,
            title: 'Biceps',
            subtitle: 'Barbell curl',
            body: 'On these I want you to do 3 sets of 8 with 90 second breaks. Use a slow 3 second eccentric when lowering the bar. 3 total work sets',
            rpe: '8-9',
          },
          {
            order: 6,
            title: 'Biceps',
            subtitle: 'Seated incline dumbell curl',
            body: 'Do 3 sets of 10 here but take 90 seconds in between sets. 3 total work sets',
            rpe: '9',
          },
          {
            order: 7,
            title: 'Abs',
            subtitle: 'Rope crunches',
            body: 'Do 4 sets to failure here. 4 total work sets',
            rpe: '9',
          },
          {
            order: 8,
            title: 'Calves',
            subtitle: 'Seated toe raises',
            body: 'Simply do 3 sets of 15 here after you are very warmed up. Tack on 5 partials on each set after your 15. Get a nice deep stretch on all reps. 3 total work sets',
            rpe: '9-10',
          },
        ],
      },
      // Friday = original Saturday pump workout
      friday: {
        isRestDay: false,
        exercises: [
          {
            order: 1,
            title: 'Chest',
            subtitle: 'Machine press',
            body: "Do these a little differently this week. Only take the weight to 3/4 lockout. Let's keep tension on pecs and bump the reps up to 15. 3 total work sets",
            rpe: '8-9',
          },
          {
            order: 2,
            title: 'Chest',
            subtitle: 'Flat dumbell press',
            body: '3 sets of 12 here only going to 3/4 lockout. 3 total work sets',
            rpe: '8-9',
          },
          {
            order: 3,
            title: 'Chest',
            subtitle: 'Cable crossover',
            body: 'Lean into these for a good stretch and do 3 sets of 12 here. 3 total work sets',
            rpe: '8-9',
          },
          {
            order: 4,
            title: 'Back',
            subtitle: 'Single arm supinated pulldown',
            body: 'We are bumping the reps a little this week. Use those single handles. Do 3 sets of 12. 3 total work sets',
            rpe: '8-9',
          },
          {
            order: 5,
            title: 'Back',
            subtitle: 'Medium/close grip pulldowns',
            body: 'If you have an attachment that allows you to do these with your palms facing each other, that is what I want. Do 3 sets of 15. 3 total work sets',
            rpe: '8-9',
          },
          {
            order: 6,
            title: 'Back',
            subtitle: 'Wide grip pulldown (partial)',
            body: 'This is simply a wide grip pulldown. I want you to take the weight down to the top of your head and hold it there and flex for 2 seconds on each rep. This is nasty. Do 3 sets of 8. 3 total work sets',
            rpe: '10',
          },
          {
            order: 7,
            title: 'Shoulders',
            subtitle:
              'Band pull apart (face pulls) / Dumbell side laterals superset',
            body: 'Exercise #1 – Band pull apart (face pulls). Exercise #2 – Dumbell side laterals. Do 3 rounds. Do 20 reps on both exercises! 6 total work sets',
            rpe: '9',
          },
        ],
      },
      saturday: { isRestDay: true, exercises: [] },
      sunday: { isRestDay: true, exercises: [] },
    },
  },
  {
    week: 3,
    days: {
      monday: {
        isRestDay: false,
        exercises: [
          {
            order: 1,
            title: 'Back',
            subtitle: 'One arm supinated pulldown',
            body: 'This is a combination I really love. We start with these, to get your lats, especially lower lats pumped. Do 4 sets of 10 here. 4 total work sets',
            rpe: '9',
          },
          {
            order: 2,
            title: 'Back',
            subtitle: 'Rack pulls',
            body: 'Do these from mid-shin. This time we are bumping the reps just a tad for hypertrophy. Lock in your lats before each rep, and then drive up hard. Find a weight that is a pretty tough 6 and do 4 sets of 6 with it. Leave a rep or two in the tank so we can get more volume here. Each rep should be a dead stop rep. No bouncing allowed! 4 total work sets',
            rpe: '9',
          },
          {
            order: 3,
            title: 'Back',
            subtitle: 'Supported chest row',
            body: "Ok let's give your lower back a break and work on those rhomboids. Use a neutral grip and really stretch and open up your rhomboids on each rep. Do 4 hard sets of 8 here too. 4 total work sets",
            rpe: '9',
          },
          {
            order: 4,
            title: 'Back',
            subtitle: 'Lat pulldown with a stretch',
            body: 'Ok here is a pulldown variation, where your partner will push down on the weight ONLY at the top for the stretch! These are an all-time favorite of mine too for the extreme stretch which can promote growth just by itself. Do 4 sets of 8 here. 4 total work sets',
            rpe: '9',
          },
          {
            order: 5,
            title: 'Back',
            subtitle: 'Hang from chin up bar',
            body: "Put a weight belt on with some weight and let's hang and stretch those lats. Stretch for as long as it takes to beat last week's time.",
            rpe: null,
          },
          {
            order: 6,
            title: 'Abs',
            subtitle: 'Decline bench leg raises',
            body: 'Do 4 sets close to failure here. 4 total work sets',
            rpe: '9',
          },
          {
            order: 7,
            title: 'Calves',
            subtitle: 'Standing raises',
            body: 'Once warmed up, do 4 sets where you do 10 full range reps, followed by 10 partials out of the bottom, followed by a 10 second stretch to end the set. Take note of your weight, keep building the weight up on these as usual. I want you using the whole stack! 4 total work sets',
            rpe: '10-11',
          },
        ],
      },
      tuesday: {
        isRestDay: false,
        exercises: [
          {
            order: 1,
            title: 'Chest',
            subtitle: 'Slight incline dumbell press',
            body: 'We are bumping reps a tad this week on these. Work your way up doing sets of 10 here. Keep going until you barely get 10 reps. The last set should be total failure. The sets working up to it, will obviously not be. We will call this 3 working sets. 3 total work sets',
            rpe: '8-10',
          },
          {
            order: 2,
            title: 'Chest',
            subtitle: 'Incline barbell press',
            body: 'I want you to do sets of 8 here moving up in weight as you go. Once you can barely squeeze out 8, that is the last set. Push as hard as you can do the same weight you did last week and still get the extra 8th rep on the last set. 3 total work sets',
            rpe: '8-10',
          },
          {
            order: 3,
            title: 'Chest',
            subtitle: 'Slight incline Smith press',
            body: 'Ok do 3 sets here working up to a weight you can hit 6 with. Once you get there, your 4th set will be a drop set. 4 total work set',
            rpe: '8-11',
          },
          {
            order: 4,
            title: 'Chest',
            subtitle: 'Dip',
            body: 'Use a machine and here and go down nice and slow and get a good stretch on every rep. Do 4 sets of 6 here. 4 total work sets',
            rpe: '10',
          },
          {
            order: 5,
            title: 'Shoulders',
            subtitle: 'Dumbell side laterals',
            body: '5 sets of 10 reps with the same weight. Take 90 second rest breaks. 5 total work sets',
            rpe: '9',
          },
          {
            order: 6,
            title: 'Shoulders',
            subtitle: 'Rear delt destroyer set',
            body: 'On these you are going to do 60 swings with a medium weight, and then drop the weight and do 30, and then one more drop for 10. This will sting a bit. 1 total work set',
            rpe: '12',
          },
        ],
      },
      wednesday: { isRestDay: false, exercises: [] }, // filled by agent
      thursday: { isRestDay: false, exercises: [] }, // filled by agent
      friday: { isRestDay: false, exercises: [] }, // filled by agent (original Saturday pump)
      saturday: { isRestDay: true, exercises: [] },
      sunday: { isRestDay: true, exercises: [] },
    },
  },
];

const weeks4to14 = require('../data/weeks_4_14.json');
const allWeeks = [...workoutData, ...weeks4to14];

module.exports = { workoutData: allWeeks, DAYS };
